// <auto-generated />
namespace HandMade.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addTimeToChat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTimeToChat));
        
        string IMigrationMetadata.Id
        {
            get { return "202004030458549_addTimeToChat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
